[project]
name = "telekinesis"
version = "0.1.0"

[app]
name = "telekinesis-gui"
kind = "gpui"
bin = "telekinesis-gui"

[[target]]
name = "tui"
kind = "tui"
source = "ui/shell.crepus"

[[target]]
name = "app"
kind = "gpui"
source = "ui/app.crepus"

[[target]]
name = "web"
kind = "ssr"
source = "ui/app.crepus"
