[project]
name = "telekinesis"
version = "0.1.0"

[[targets]]
type = "gpui"
id = "gui"
path = "ui/gui"

[[targets]]
type = "tui"
id = "tui"
path = "ui/tui"

[[targets]]
type = "web"
id = "web"
path = "ui/web"
